### ISSUE TITLE
When can MAVSDK-Go be used for production?

### ISSUE THREAD

**Issue by sunxueyi888** [mavlink/MAVSDK-Go#5]
When can MAVSDK-Go be used for production?

**Comment by JonasVautherin** [comment]
Did you try it?

**Comment by sunxueyi888** [comment]
go 1.19.4
MAVSDK-Go-main\system\system.go
116，117 row There are errors.
116:Polygon_FENCE_TYPE_EXCLUSION not declared by package geofence
117:cannot use ([]*geofence.Polygon literal) (value of type []*geofence.Polygon) as *geofence.GeofenceData value in argument to drone.geofence.UploadGeofence

**Comment by JonasVautherin** [comment]
@ykhedar would you have some advice here? :innocent:

**Comment by ykhedar** [comment]
Hi, There were some problems with the generated sources from the last PR, which should be fixed with the latest commit. Could you please try again @sunxueyi888 ?

As for readiness, we use the module in our company and have had not much problem until now. Always open to feedback/ bug reports though :)

**Comment by sunxueyi888** [comment]
It's ready to run, thank you
